// Writes vercel.json and public/_headers (Netlify / Cloudflare Pages) from security-headers.json,
// the single source of truth. Run after editing headers: node scripts/sync-headers.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const headers = JSON.parse(fs.readFileSync(path.join(root, 'security-headers.json'), 'utf8'));
const entries = Object.entries(headers);

const immutable = 'public, max-age=31536000, immutable';
const vercel = {
  $schema: 'https://openapi.vercel.sh/vercel.json',
  cleanUrls: true,
  headers: [
    { source: '/(.*)', headers: entries.map(([key, value]) => ({ key, value })) },
    { source: '/assets/(.*)', headers: [{ key: 'Cache-Control', value: immutable }] },
    { source: '/fonts/(.*)', headers: [{ key: 'Cache-Control', value: 'public, max-age=2592000' }] },
    { source: '/models/(.*)', headers: [{ key: 'Cache-Control', value: 'public, max-age=2592000' }] },
    { source: '/', headers: [{ key: 'Cache-Control', value: 'public, max-age=0, must-revalidate' }] },
  ],
};
fs.writeFileSync(path.join(root, 'vercel.json'), `${JSON.stringify(vercel, null, 2)}\n`);

const netlify = [
  '# Generated by scripts/sync-headers.mjs from security-headers.json — do not edit by hand.',
  '/*',
  ...entries.map(([key, value]) => `  ${key}: ${value}`),
  '',
  '/assets/*',
  `  Cache-Control: ${immutable}`,
  '',
  '/fonts/*',
  '  Cache-Control: public, max-age=2592000',
  '',
  '/models/*',
  '  Cache-Control: public, max-age=2592000',
  '',
].join('\n');
fs.writeFileSync(path.join(root, 'public', '_headers'), netlify);
console.log('wrote vercel.json and public/_headers');
